### PR TITLE
Add package.json for npm publishing

### PR DESCRIPTION
**Pull request by arichiardi**
This library is awesome, as lumo works out of the box.

In my quest to use npm as package manager to lumo libs, I am contributing the
`package.json` file to a bunch of projects.

I hope you are interested, if not let me know, no problem :)

I will also add the project here
https://github.com/anmonteiro/lumo/wiki/Compatible-libraries.

### CODE REVIEW

**Comment by huahaiy** [comment]
Merged, thanks for contributing.

**Comment by arichiardi** [comment]
Thank you! Let me know when you publish so I can drop my local one :)

**Comment by huahaiy** [comment]
Sure. Here you go: https://www.npmjs.com/package/clj-editscript
Had to change to clj-editscript because npm said "Package name too similar to existing packages"...

**Comment by arichiardi** [comment]
Great super cool thank you a ton!

**Pull request merged**
